Consolidate and Update Sample for Rails 6
auth0-samples/auth0-rubyonrails-sample pull request #47
Opened 2021-02-03 21:19 UTC by davidpatrick

- Migrates from secrets to config_for
- Adds non-interactive formpost redirect
- Consolidates samples into one easy to use sample
- Migrates to Rails 6

closes https://github.com/auth0-samples/auth0-rubyonrails-sample/issues/43

2021-02-04 10:44 UTC, frederikprijck requested changes

2021-02-04 10:44 UTC, frederikprijck commented on sample/config/initializers/auth0.rb
> +    Rails.application.config.auth0['auth0_domain'],
Same question here as in the quickstart review (https://github.com/auth0/docs/pull/9603), is there any reason this can not use : `auth_config['auth0_domain']` (or `auth_config.auth0_domain.`)?

2021-02-19 15:22 UTC, stevehobbsdev approved these changes

2021-02-20 06:17 UTC, frederikprijck approved these changes

2021-03-10 00:04 UTC, merged